### ISSUE TITLE
Sort Announcement table by headings.

### ISSUE THREAD

**Issue by jvansant** [opustm/mvp-frontend#66]
There is already an easy-to-use table sorting tool out there. 

Update: found it. just add the script in shazam. sorted. easy.
https://datatables.net/examples/basic_init/table_sorting.html

**Comment by willda07** [comment]
This is similar to #39, can probably be done in a similar manner

**Comment by willda07** [comment]
I will do this in a pull request after the MVP checkpoint but before the MVP when I go through and fix bugs. Not a big priority at the moment.
